export const TOGGLE_THEME = 'TOGGLE_THEME';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_CLEAN = 'SEARCH_CLEAN';

export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS';
export const GET_ALL_EPISODES = 'GET_ALL_EPISODES';
export const GET_ALL_LOCATIONS = 'LOCATIONS';




